# Generated by Django 5.2.7 on 2025-11-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='altura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='animais/'),
        ),
        migrations.AddField(
            model_name='animal',
            name='peso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
