# Generated by Django 5.2.7 on 2025-11-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutores', '0002_animal_altura_animal_foto_animal_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='microchip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('passaro', 'Pássaro'), ('outro', 'Outro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, default='animais/default_animal.jpg', null=True, upload_to='animais/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(blank=True, choices=[('labrador', 'Labrador'), ('poodle', 'Poodle'), ('persa', 'Persa'), ('siames', 'Siamês'), ('canario', 'Canário'), ('outro', 'Outro')], max_length=50),
        ),
    ]
