# Generated by Django 5.2.7 on 2025-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clinicas/'),
        ),
    ]
