# Generated by Django 5.2.7 on 2025-11-20 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0002_clinica_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinica',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='localizacao_placeholder',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='nome_fantasia',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='veterinario',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='clinica',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='nome',
            field=models.CharField(default='Clinica Padrão', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='veterinario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinica', to='veterinarios.veterinario'),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='crmv',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
