# Generated by Django 5.2.7 on 2025-11-20 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0003_remove_clinica_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinicas', to='veterinarios.veterinario'),
        ),
    ]
