# Generated by Django 5.2.7 on 2025-11-20 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0004_alter_clinica_veterinario'),
    ]

    operations = [
    ]
